name: 3DS Homebrew Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    
    env:
      DEVKITPRO: /opt/devkitpro
      DEVKITARM: /opt/devkitpro/devkitARM
      PATH: /opt/devkitpro/devkitARM/bin:/opt/devkitpro/tools/bin:/opt/devkitpro/pacman/bin:/usr/local/bin:/usr/bin:/bin

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install 3DS Dev Kit
      run: |
        /opt/devkitpro/pacman/bin/pacman -Sy --noconfirm 3ds-dev

    - name: Compile
      run: |
        make clean
        # 【修正】外からの強制上書きをやめ、Makefile本来の設定で安全にビルドします！
        make

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: 3ds-homebrew-file
        path: |
          *.3dsx
          *.cia
