name: 3DS Homebrew Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run build in devkitpro container
      uses: addnab/docker-run-action@v3
      with:
        image: devkitpro/devkitarm:latest
        options: -v ${{ github.workspace }}:/workspace
        run: |
          dkp-pacman -S --noconfirm 3ds-dev
          cd /workspace
          make
          
    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: 3ds-homebrew-file
        path: |
          *.3dsx
          *.cia
